### ISSUE TITLE
Doesn't work with PS7

### ISSUE THREAD

**Issue by blackerking** [awarre/Optimize-WsusServer#1]
After invensting some time its getting clear that the latest version of powershell (7) doesn't work with the api of WSUS.
Maybe a clear issue from microsoft but I think a worthy note for the readme file.

https://windowsserver.uservoice.com/forums/304618-installation-and-patching/suggestions/39267028-wsus-server-should-be-manageable-using-powershell

**Comment by solarplex** [comment]
Looking into that, it seems that .NET is the problem since PS7 using Core and the WSUS team has not switched over yet (supposedly). Looks like from the MSFT team they said the WSUS team wont be ready at the launch of ps7. no word from the WSUS team. Hopefully they open source at some point.

**Comment by awarre** [comment]
Thanks, I've updated the README to reflect this. Unfortunately it is outside of my ability to update the official WSUS PS module with PowerShell 7 support!

**Comment by awarre** [comment]
Thanks, I've updated the README to reflect this. Unfortunately it is outside of my ability to update the official WSUS PS module with PowerShell 7 support!
