### ISSUE TITLE
Get-WsusIISLocalizedNamespacePath doesn't exist

### ISSUE THREAD

**Issue by UnknwnSoldier** [awarre/Optimize-WsusServer#12]
This line in the script references a cmdlet that as as far as I can tell doesn't exist.   Web search returns no results for this cmdlet.

$iisPath = Get-WsusIISLocalizedNamespacePath

It generates the following error on my system:

Get-WsusIISLocalizedNamespacePath : The term 'Get-WsusIISLocalizedNamespacePath' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.

**Comment by rismoney** [comment]
I moved that function (from the middle of the script) to the top of the script, and it worked...

**Comment by awarre** [comment]
Thanks @UnknwnSoldier, this should be fixed now in the current master and 1.2.1 release.
