### ISSUE TITLE
Permissions on ClientWebService\web.config

### ISSUE THREAD

**Issue by bargibargi** [awarre/Optimize-WsusServer#15]
Might help someone.
Script failed to update settings in there as by defualt Administrators don't have Full Access to the file (couldn't update via IIS admin either)
This was Server 2019 if it makes a difference.

Resolved with the following.

Open an elevated Command Prompt window, and then go to the following location:
%programfiles%\Update Services\WebServices\ClientWebService
Type the following commands, and press Enter after each command:
takeown /f web.config
icacls web.config /grant administrators:(F)

**Comment by awarre** [comment]
@bargibargi v1.2.1 should have resolved this.

1. Is your WSUS install using English? The original release had issues with finding the IIS site for non-English installations.
2. What version of the script are you running?

**Comment by bargibargi** [comment]
It's English and latest script.
But this server has been renamed in the past and in IIS it does have the original server name when connecting via admin console.
So sounds like that might be the reason

**Comment by awarre** [comment]
@bargibargi thanks for the update and information. I can't duplicate this scenario and you have a working solution for your particular situation, so I'm going to close this.
