### ISSUE TITLE
SQL server not supported

### ISSUE THREAD

**Issue by jwiermans** [awarre/Optimize-WsusServer#7]
Hi,

Thanks for the script. love it.

Unfortunately your script doesn't support (remote) SQL Server as WSUS database.

By simply adding: `$ServerInstance = $wsusSqlServerName` in the last else-clause of the `Optimize-WsusDatabase` function and commenting out the current line, the script will also support (remote) SQL Server. Sweet!

**Comment by awarre** [comment]
@
